version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "MAINT:"

  - package-ecosystem: "docker"
    directory: "/smoketest"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "MAINT:"
  - package-ecosystem: "pip"
    directory: "/smoketest"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "MAINT:"
