apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- github.com/ZeitOnline/kustomize/components/nightwatch?ref=1.16.1
- versions

resources:
- secrets.yaml


patches:
- target:
    kind: Deployment
    name: nightwatch
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: VIVI_XMLRPC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: principals
            key: vivi_zeit.cms.principals_system.nightwatch
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: TMS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tms
            key: vivi_zeit.retresco_password

# See https://github.com/ZeitOnline/gh-action-workflows/blob/main/.github/workflows/nightwatch-build.yaml
images:
- name: nightwatch
  newName: europe-west3-docker.pkg.dev/zeitonline-engineering/docker-zon/vivi-nightwatch
