apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- github.com/ZeitOnline/kustomize/components/nightwatch?ref=1.3
- versions

# See https://github.com/ZeitOnline/gh-action-workflows/blob/main/.github/workflows/nightwatch-build.yaml
images:
- name: nightwatch
  newName: europe-west3-docker.pkg.dev/zeitonline-engineering/docker-zon/vivi-nightwatch
