apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: activedirectory

spec:
  refreshInterval: 10m
  secretStoreRef:
    name: baseproject-vault
    kind: SecretStore
  data:
  - secretKey: AD_CLIENT_ID
    remoteRef:
      key: zon/v1/azure/activedirectory/oidc/staging/vivi
      property: client_id
  - secretKey: AD_CLIENT_SECRET
    remoteRef:
      key: zon/v1/azure/activedirectory/oidc/staging/vivi
      property: client_secret
  - secretKey: AD_REFRESH_TOKEN
    remoteRef:
      key: zon/v1/azure/activedirectory/oidc/staging/vivi
      property: refresh_token