repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: debug-statements
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.3
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
    types_or: [python, pyi]
  - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.36.0'
    hooks:
    -   id: eslint
        additional_dependencies:
          - eslint
          - "@eslint/js"
          - globals
