from setuptools import setup, find_packages


setup(
    name='zeit.securitypolicy',
    version='2.2.5',
    author='gocept, Zeit Online',
    author_email='zon-backend@zeit.de',
    url='http://www.zeit.de/',
    description="vivi roles and permissions",
    packages=find_packages('src'),
    package_dir={'': 'src'},
    include_package_data=True,
    zip_safe=False,
    license='BSD',
    namespace_packages=['zeit'],
    install_requires=[
        'plone.testing',
        'setuptools',
        'xlrd',
        'zeit.brightcove',
        'zeit.calendar',
        'zeit.cms>=3.5.0.dev0',
        'zeit.content.article',
        'zeit.content.cp >= 2.10.0.dev0',
        'zeit.content.image>=2.6.0.dev0',
        'zeit.content.link',
        'zeit.content.quiz',
        'zeit.content.rawxml',
        'zeit.content.text',
        'zeit.content.video',
        'zeit.invalidate',
        'zeit.retresco>=1.19.0.dev0',
        'zeit.seo>=1.6.0.dev0',
        'zope.app.zcmlfiles',
    ],
)
