apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nightwatch-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: baseproject-vault
    kind: SecretStore
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: zon/v1/keycloak/production/zeit-online/edge-www
      property: client_id
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: zon/v1/keycloak/production/zeit-online/edge-www
      property: client_secret
