apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- target:
    kind: Deployment
    name: nightwatch
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - "--nightwatch-environment=production"
- target:
    kind: ExternalSecret
    name: nightwatch-secrets
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: zon/v1/azure/activedirectory/oidc/production/vivi
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: zon/v1/azure/activedirectory/oidc/production/vivi
    - op: replace
      path: /spec/data/2/remoteRef/key
      value: zon/v1/azure/activedirectory/oidc/production/vivi
