[project]
name = "vivi-nightwatch"
version = "0.0.1"
requires-python = ">=3.13"

dependencies = ["zeit.nightwatch", "zeit.msal", "behave"]

[[tool.uv.index]]
name = "pypi-zon"
url = "https://europe-west3-python.pkg.dev/zeitonline-engineering/pypi-zon/simple/"
default = true
